CREATE TABLE IF NOT EXISTS interconsulta_paciente (
  id INT NOT NULL AUTO_INCREMENT,
  cod_interConsultaFK INT NOT NULL,
  cedula VARCHAR(60) NOT NULL,
  cedula_normalizada VARCHAR(60) NOT NULL,
  cod_clienteFK_principal INT NULL,
  nombre_paciente_snapshot VARCHAR(150) NULL,
  estado_conflicto TINYINT(1) NOT NULL DEFAULT 0,
  detalle_conflicto VARCHAR(255) NULL,
  ventas_sin_plan_madre INT NOT NULL DEFAULT 0,
  total_ventas INT NOT NULL DEFAULT 0,
  total_planes_madre INT NOT NULL DEFAULT 0,
  origen VARCHAR(30) NOT NULL DEFAULT 'automatico',
  estado VARCHAR(20) NOT NULL DEFAULT 'activo',
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cod_usuarioFK_create INT NULL,
  fecha_actualizacion DATETIME NULL,
  cod_usuarioFK_update INT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_interconsulta_paciente_cedula (cedula_normalizada),
  KEY idx_interconsulta_paciente_hilo (cod_interConsultaFK),
  KEY idx_interconsulta_paciente_cliente (cod_clienteFK_principal),
  KEY idx_interconsulta_paciente_conflicto (estado_conflicto),
  KEY idx_interconsulta_paciente_estado (estado)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;

CREATE TABLE IF NOT EXISTS interconsulta_paciente_venta (
  id INT NOT NULL AUTO_INCREMENT,
  cod_interConsultaFK INT NOT NULL,
  cod_ventaFK INT NOT NULL,
  cedula_normalizada VARCHAR(60) NOT NULL,
  cod_clienteFK INT NULL,
  plan_madre_id INT NULL,
  estado VARCHAR(20) NOT NULL DEFAULT 'activo',
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  cod_usuarioFK_create INT NULL,
  fecha_actualizacion DATETIME NULL,
  cod_usuarioFK_update INT NULL,
  PRIMARY KEY (id),
  UNIQUE KEY uq_interconsulta_paciente_venta (cod_ventaFK),
  KEY idx_interconsulta_paciente_venta_hilo (cod_interConsultaFK),
  KEY idx_interconsulta_paciente_venta_cedula (cedula_normalizada),
  KEY idx_interconsulta_paciente_venta_plan (plan_madre_id)
) ENGINE=InnoDB DEFAULT CHARSET=latin1 COLLATE=latin1_swedish_ci;
