CREATE TABLE IF NOT EXISTS solicitudes_ausencia (
  id INT NOT NULL AUTO_INCREMENT,
  cod_usuarioFK INT NOT NULL,
  tipo VARCHAR(30) NOT NULL,
  fecha_desde DATE NOT NULL,
  fecha_hasta DATE NOT NULL,
  hora_desde TIME DEFAULT NULL,
  hora_hasta TIME DEFAULT NULL,
  motivo VARCHAR(500) DEFAULT NULL,
  archivo_url VARCHAR(255) DEFAULT NULL,
  archivo_nombre VARCHAR(180) DEFAULT NULL,
  estado VARCHAR(30) NOT NULL DEFAULT 'pendiente',
  creado_por INT DEFAULT NULL,
  aprobado_por INT DEFAULT NULL,
  fecha_creacion DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  fecha_aprobacion DATETIME DEFAULT NULL,
  observacion_aprobacion VARCHAR(500) DEFAULT NULL,
  origen VARCHAR(80) DEFAULT NULL,
  visto_rrhh TINYINT(1) NOT NULL DEFAULT 0,
  PRIMARY KEY (id),
  KEY idx_solicitudes_ausencia_usuario_fecha (cod_usuarioFK, fecha_desde, fecha_hasta),
  KEY idx_solicitudes_ausencia_estado (estado),
  KEY idx_solicitudes_ausencia_tipo (tipo)
) ENGINE=InnoDB DEFAULT CHARSET=latin1;
