CREATE TABLE IF NOT EXISTS recetario_firmas (
    id INT(11) NOT NULL AUTO_INCREMENT,
    recetario_id INT(11) NOT NULL,
    usuario_firmante_id INT(11) NOT NULL,
    nombre_firmante_snapshot VARCHAR(180) NOT NULL,
    usuario_emisor_id INT(11) NOT NULL,
    nombre_emisor_snapshot VARCHAR(180) NOT NULL,
    firma_imagen_path VARCHAR(255) NOT NULL,
    firma_base64 LONGTEXT DEFAULT NULL,
    fecha_hora_firma DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    hash_documento CHAR(64) DEFAULT NULL,
    hash_firma CHAR(64) DEFAULT NULL,
    ip VARCHAR(45) DEFAULT NULL,
    user_agent VARCHAR(500) DEFAULT NULL,
    dispositivo VARCHAR(80) DEFAULT NULL,
    estado ENUM('vigente','invalida','anulada') NOT NULL DEFAULT 'vigente',
    created_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
    PRIMARY KEY (id),
    KEY idx_recetario_firmas_recetario_estado (recetario_id, estado),
    KEY idx_recetario_firmas_usuario_fecha (usuario_firmante_id, fecha_hora_firma),
    CONSTRAINT fk_recetario_firmas_recetario FOREIGN KEY (recetario_id) REFERENCES recetarios_indicaciones(id) ON DELETE CASCADE,
    CONSTRAINT fk_recetario_firmas_firmante FOREIGN KEY (usuario_firmante_id) REFERENCES usuario(cod_usuario),
    CONSTRAINT fk_recetario_firmas_emisor FOREIGN KEY (usuario_emisor_id) REFERENCES usuario(cod_usuario)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb3 COLLATE=utf8mb3_general_ci;
