SELECT TABLE_NAME
FROM INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME IN ('seguridad', 'usuario')
ORDER BY TABLE_NAME;

SELECT TABLE_NAME, COLUMN_NAME, COLUMN_TYPE, COLUMN_KEY, EXTRA
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = DATABASE()
  AND (
    (TABLE_NAME = 'seguridad' AND COLUMN_NAME IN ('id', 'id_usuario', 'navegador', 'pass'))
    OR
    (TABLE_NAME = 'usuario' AND COLUMN_NAME IN ('cod_usuario', 'estado'))
  )
ORDER BY TABLE_NAME, ORDINAL_POSITION;

SELECT INDEX_NAME, GROUP_CONCAT(COLUMN_NAME ORDER BY SEQ_IN_INDEX) AS columnas
FROM INFORMATION_SCHEMA.STATISTICS
WHERE TABLE_SCHEMA = DATABASE()
  AND TABLE_NAME = 'seguridad'
GROUP BY INDEX_NAME
ORDER BY INDEX_NAME;
