(function () {
    "use strict";

    var estado = { pagina: 1, paginas: 1, limite: 25, cargando: false, localesCargados: false, filas: [] };
    function el(id) { return document.getElementById(id); }
    function texto(v) { return String(v == null ? "" : v).replace(/[&<>"']/g, function (c) { return { "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" }[c]; }); }
    function numero(v) { return Number(v || 0).toLocaleString("es-PY"); }
    function fecha(v, hora) { if (!v) return "Sin fecha"; var d = String(v).split(" "); var p = d[0].split("-"); return (p.length === 3 ? p[2] + "/" + p[1] + "/" + p[0] : d[0]) + (hora && d[1] ? " " + d[1].slice(0, 5) : ""); }
    function credenciales(d) { d.append("useru", typeof userid !== "undefined" ? userid : ""); d.append("passu", typeof passuser !== "undefined" ? passuser : ""); d.append("navegador", typeof navegador !== "undefined" ? navegador : ""); return d; }
    function aviso(m, tipo) { var n = el("hpsAviso"); if (!n) return; n.hidden = !m; n.className = "cs-notice cs-notice--" + (tipo || "info"); n.textContent = m || ""; }
    function filtros(limite, pagina) { var d = credenciales(new FormData()); d.append("pagina", pagina || estado.pagina); d.append("limite", limite || estado.limite); ["buscar", "venta", "local", "desde", "hasta"].forEach(function (c) { var n = el("hpsFiltro" + c.charAt(0).toUpperCase() + c.slice(1)); d.append(c, n ? n.value : ""); }); return d; }
    function setCargando(v) { estado.cargando = v; var n = el("hpsCargando"); if (n) n.hidden = !v; var b = el("btnHpsBuscar"); if (b) b.disabled = v; }
    function error(r) { if (r && r["1"] === "UI") { if (typeof sesionFinalizada === "function") sesionFinalizada(); else window.location.href = "/GoodVentaAsisCap/system/login.php?cerrar=1"; return true; } if (!r || r["1"] !== "exito") { aviso((r && r["2"]) || "No se pudo consultar el historial.", "error"); return true; } return false; }
    function locales(r) { var n = el("hpsFiltroLocal"); if (!n || estado.localesCargados) return; if (!r.puede_cambiar_local) { n.closest("label").hidden = true; estado.localesCargados = true; return; } n.innerHTML = '<option value="">Todos los locales</option>' + (r.locales || []).map(function (l) { return '<option value="' + l.id + '">' + texto(l.nombre) + '</option>'; }).join(""); estado.localesCargados = true; }
    function resumen(r) { var x = r.resumen || {}; var m = { hpsResumenClientes: x.clientes, hpsResumenVentas: r.total, hpsResumenCuotas: x.cuotas, hpsResumenSaldo: "Gs. " + numero(x.saldo), hpsResumenVencidas: x.vencidas, hpsResumenParciales: x.parciales }; Object.keys(m).forEach(function (id) { if (el(id)) el(id).textContent = typeof m[id] === "string" ? m[id] : numero(m[id]); }); }
    function tabla(filas) { estado.filas = filas || []; var c = el("hpsTablaCuerpo"), v = el("hpsVacio"); if (!c) return; c.innerHTML = estado.filas.map(function (f) { var vencida = f.primer_vencimiento && f.primer_vencimiento < new Date().toISOString().slice(0, 10); return '<tr><td><b>' + texto(f.cliente || ("Cliente " + f.cliente_id)) + '</b><small>Doc. ' + texto(f.documento || "Sin documento") + '<br>' + texto(f.telefono || "Sin tel\u00e9fono") + '</small></td><td><b>#' + f.venta + '</b><small>' + texto(f.factura || "Sin factura") + '<br>' + texto(f.local || "Sin local") + '</small></td><td><span class="cs-sequence cs-sequence--paid">' + texto(f.cuotas_pagadas || "-") + '</span></td><td><span class="cs-sequence cs-sequence--gap">' + texto(f.cuotas_pendientes || "-") + '</span><small>' + f.cuotas_salteadas + ' cuota(s), ' + f.cuotas_parciales + ' parcial(es)</small></td><td><span class="cs-due ' + (vencida ? "is-overdue" : "") + '">' + fecha(f.primer_vencimiento) + '</span></td><td>' + (Number(f.tiene_entrega) === 1 ? '<span class="cs-delivery"><b>Entrega: Gs. ' + numero(f.monto_entrega) + '</b><small>Pagado: Gs. ' + numero(f.pagado_entrega) + '</small></span>' : '<span class="cs-no-delivery">\u2014</span>') + '</td><td class="cs-money">Gs. ' + numero(f.saldo) + '</td><td><div class="cs-row-actions"><button type="button" onclick="historialPagosSalteadosDetalle(' + f.id + ')">Ver detalle</button></div></td></tr>'; }).join(""); if (v) v.hidden = estado.filas.length > 0; }
    function detalle(id) { var d = credenciales(new FormData()), panel = el("hpsDetalle"), contenido = el("hpsDetalleContenido"); d.append("funt", "detalle"); d.append("id", id); if (panel) panel.hidden = false; if (contenido) contenido.innerHTML = '<div class="cs-detail-loading">Cargando cuotas guardadas...</div>'; fetch("/GoodVentaAsisCap/php_system/abmHistorialPagosSalteados.php", { method: "POST", body: d, credentials: "same-origin" }).then(function (r) { return r.text(); }).then(function (t) { try { return JSON.parse(t); } catch (e) { throw new Error("Respuesta inv\u00e1lida del servidor"); } }).then(function (r) { if (error(r) || !contenido) return; contenido.innerHTML = '<div class="cs-detail-summary"><div><b>Venta #' + r.venta + '</b><span>' + texto(r.cliente || "") + '</span></div><span>Guardado: ' + fecha(r.fecha_deteccion, true) + '</span></div><div class="cs-detail-legend"><span class="is-paid">Pagada</span><span class="is-skipped">Salteada</span><span class="is-pending">Pendiente</span></div><div class="cs-detail-list">' + (r.cuotas || []).map(function (c) { var salteada = Number(c.salteada) === 1, clase = salteada ? "skipped" : (Number(c.pagada) === 1 ? "paid" : (c.estado === "Pago parcial" ? "partial" : (c.estado === "Vencida" ? "overdue" : (c.estado === "Sin monto" ? "zero" : "pending")))); return '<article class="cs-detail-item is-' + clase + '"><div><b>Cuota ' + texto(c.plazo) + '</b><span>Cr\u00e9dito #' + c.credito + ' \u00b7 Vencimiento: ' + fecha(c.vencimiento) + '</span></div><span class="cs-status">' + texto(salteada ? (c.estado === "Pago parcial" ? "Salteada \u00b7 Pago parcial" : "Salteada") : c.estado) + '</span><div class="cs-detail-amounts"><span>Capital: Gs. ' + numero(c.capital_pagado) + ' / ' + numero(c.capital_debido) + '</span><span>Inter\u00e9s: Gs. ' + numero(c.interes_pagado) + ' / ' + numero(c.interes_debido) + '</span><span>Total pagado: Gs. ' + numero(Number(c.capital_pagado) + Number(c.interes_pagado)) + '</span><b>Saldo: Gs. ' + numero(c.saldo) + '</b></div></article>'; }).join("") + '</div>'; }).catch(function (e) { if (contenido) contenido.innerHTML = '<div class="cs-empty">' + texto(e.message || "No se pudo cargar el detalle guardado.") + '</div>'; }); }
    function paginacion() { var n = el("hpsPaginacion"); if (!n) return; n.innerHTML = '<button type="button" ' + (estado.pagina <= 1 ? "disabled" : "") + ' onclick="historialPagosSalteadosPagina(' + (estado.pagina - 1) + ')">Anterior</button><span>P\u00e1gina <b>' + estado.pagina + '</b> de <b>' + estado.paginas + '</b></span><button type="button" ' + (estado.pagina >= estado.paginas ? "disabled" : "") + ' onclick="historialPagosSalteadosPagina(' + (estado.pagina + 1) + ')">Siguiente</button>'; }
    function cargar() { if (estado.cargando) return; setCargando(true); aviso(""); fetch("/GoodVentaAsisCap/php_system/abmHistorialPagosSalteados.php", { method: "POST", body: filtros(), credentials: "same-origin" }).then(function (r) { return r.text(); }).then(function (t) { try { return JSON.parse(t); } catch (e) { throw new Error("Respuesta inv\u00e1lida del servidor"); } }).then(function (r) { if (error(r)) return; estado.pagina = Number(r.pagina || 1); estado.paginas = Number(r.paginas || 1); locales(r); resumen(r); tabla(r.filas); paginacion(); }).catch(function (e) { aviso(e.message || "No se pudo consultar el historial.", "error"); }).finally(function () { setCargando(false); }); }
    window.verCerrarHistorialPagosSalteados = function (abrir) { var n = el("divHistorialPagosSalteados"); if (!n) return; n.style.display = abrir ? "flex" : "none"; if (abrir) { estado.pagina = 1; cargar(); } else { window.historialPagosSalteadosCerrarDetalle(); } };
    window.historialPagosSalteadosBuscar = function () { estado.pagina = 1; cargar(); };
    window.historialPagosSalteadosPagina = function (p) { if (p >= 1 && p <= estado.paginas) { estado.pagina = p; cargar(); } };
    window.historialPagosSalteadosDetalle = detalle;
    window.historialPagosSalteadosCerrarDetalle = function () { var n = el("hpsDetalle"); if (n) n.hidden = true; };
    window.historialPagosSalteadosLimpiar = function () { ["Buscar", "Venta", "Local", "Desde", "Hasta"].forEach(function (n) { if (el("hpsFiltro" + n)) el("hpsFiltro" + n).value = ""; }); estado.pagina = 1; cargar(); };
    document.addEventListener("keydown", function (e) { if (e.key === "Escape") window.historialPagosSalteadosCerrarDetalle(); });
}());
