-- Compatibilidad del comportamiento legacy de MySQL 5.6 con MariaDB en modo estricto.
-- Hace explicitos solamente valores que el servidor anterior completaba como 0 o cadena vacia.

ALTER TABLE accesosuser
    MODIFY COLUMN frmname VARCHAR(75) NOT NULL DEFAULT '',
    MODIFY COLUMN orden DOUBLE NOT NULL DEFAULT 0;

ALTER TABLE compra
    MODIFY COLUMN total_compra DOUBLE NOT NULL DEFAULT 0,
    MODIFY COLUMN tipo_comprobante VARCHAR(20) NOT NULL DEFAULT '',
    MODIFY COLUMN motivoeliminar VARCHAR(150) NOT NULL DEFAULT '';

ALTER TABLE credito
    MODIFY COLUMN dias DOUBLE NOT NULL DEFAULT 0,
    MODIFY COLUMN interes DOUBLE NOT NULL DEFAULT 0,
    MODIFY COLUMN totalinteres INT(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN totaldeuda INT(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN total INT(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN descuento INT(11) NOT NULL DEFAULT 0;

ALTER TABLE fotos_cliente
    MODIFY COLUMN cod_ventaFK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE historialdespacho
    MODIFY COLUMN cod_anulado_por VARCHAR(45) NOT NULL DEFAULT '',
    MODIFY COLUMN fecha_anulacion DATE NULL DEFAULT NULL;

ALTER TABLE nrofactura
    MODIFY COLUMN timbrado VARCHAR(20) NOT NULL DEFAULT '',
    MODIFY COLUMN ire VARCHAR(5) NOT NULL DEFAULT '',
    MODIFY COLUMN irp VARCHAR(5) NOT NULL DEFAULT '',
    MODIFY COLUMN iva VARCHAR(5) NOT NULL DEFAULT '';

ALTER TABLE pago
    MODIFY COLUMN codApertura VARCHAR(45) NOT NULL DEFAULT '',
    MODIFY COLUMN codCaja VARCHAR(45) NOT NULL DEFAULT '',
    MODIFY COLUMN descripcion VARCHAR(45) NOT NULL DEFAULT '',
    MODIFY COLUMN cod_tipoPagoFK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE pagoseliminados
    MODIFY COLUMN cod_ventaFK VARCHAR(10) NOT NULL DEFAULT '';

ALTER TABLE pedidos
    MODIFY COLUMN idpedidos INT(11) NOT NULL AUTO_INCREMENT;

ALTER TABLE persona
    MODIFY COLUMN direccion VARCHAR(255) NOT NULL DEFAULT '';

ALTER TABLE producto
    MODIFY COLUMN stock_producto DOUBLE NOT NULL DEFAULT 0;

ALTER TABLE referenciascliente
    MODIFY COLUMN obs VARCHAR(250) NOT NULL DEFAULT '';

ALTER TABLE solicitudcredito
    MODIFY COLUMN detalleVenta VARCHAR(100) NOT NULL DEFAULT '',
    MODIFY COLUMN cod_usuarioFK INT(11) NOT NULL DEFAULT 0;

ALTER TABLE venta
    MODIFY COLUMN pago INT(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN descuento INT(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN codSolicitudCreditoFK INT(11) NOT NULL DEFAULT 0,
    MODIFY COLUMN apodo VARCHAR(50) NOT NULL DEFAULT '';
